table ComplianceTrackingTable
	lineageTag: 6ae5b441-1c3a-4ade-9a10-139511a79146

	measure 'Échéances suivies' = COUNTROWS(ComplianceTrackingTable)
		formatString: 0
		lineageTag: 935268b5-c378-4449-893d-53c96ab29a0d

	measure 'Obligations suivies' = DISTINCTCOUNT(ComplianceTrackingTable[Obligation_ID])
		formatString: 0
		lineageTag: 2e15d9c7-9caa-4862-b8b7-c5f9c8677d2f

	measure 'Échéances conformes' = [Dossiers à jour]
		formatString: 0
		lineageTag: eb844e53-92f8-4310-9574-cb42c6dace0b

	measure 'Échéances à traiter' = [Actions immédiates]
		formatString: 0
		lineageTag: 43cb74a9-c303-4e29-a377-bb7481963734

	measure 'Taux de conformité' =
			VAR BaseÉvaluable = [Dossiers à jour] + [Actions immédiates]
			RETURN DIVIDE([Dossiers à jour], BaseÉvaluable)
		formatString: 0.0%
		lineageTag: 44d0dfc0-e5e0-4599-9158-3c00507b1f49

	measure 'Échéances dans 30 jours' = [À faire bientôt]
		formatString: 0
		lineageTag: 5b046117-da6f-4d69-ae10-54cdecd8cacc

	measure 'Dossiers à jour' =
			COALESCE(
			    CALCULATE(
			        COUNTROWS(ComplianceTrackingTable),
			        FILTER(ComplianceTrackingTable, ComplianceTrackingTable[Statut opérationnel] IN {"À jour", "Fait hors délai"})
			    ),
			    0
			)
		formatString: 0
		lineageTag: 3b60ee55-d714-4f67-92cf-875b95bbdb15

	measure 'Actions immédiates' =
			COALESCE(
			    CALCULATE(
			        COUNTROWS(ComplianceTrackingTable),
			        FILTER(ComplianceTrackingTable, ComplianceTrackingTable[Statut opérationnel] IN {"En retard", "Paiement en attente", "Écart à justifier", "Urgent"})
			    ),
			    0
			)
		formatString: 0
		lineageTag: 6ee4691f-e13b-4d3d-9a97-5255676c8cad

	measure 'À faire bientôt' =
			COALESCE(
			    CALCULATE(
			        COUNTROWS(ComplianceTrackingTable),
			        FILTER(ComplianceTrackingTable, ComplianceTrackingTable[Statut opérationnel] = "À faire bientôt")
			    ),
			    0
			)
		formatString: 0
		lineageTag: a1adec64-4260-4a3c-b3f9-8113e13c56f2

	measure 'Dossiers à confirmer' =
			COALESCE(
			    CALCULATE(
			        COUNTROWS(ComplianceTrackingTable),
			        FILTER(ComplianceTrackingTable, ComplianceTrackingTable[Statut opérationnel] = "À confirmer")
			    ),
			    0
			)
		formatString: 0
		lineageTag: 9d9e2d57-426c-40a8-92dd-a5bfd3a7a0b8

	measure 'Montant restant à payer' =
			SUMX(
			    ComplianceTrackingTable,
			    MAX(0, COALESCE(ComplianceTrackingTable[Montant_Dû], 0) - COALESCE(ComplianceTrackingTable[Montant_Payé], 0))
			)
		formatString: #,0
		lineageTag: fbcd8f99-07b4-4c73-857b-d1c1a23adff8

	measure 'Montant restant affiché' =
			VAR Montant = [Montant restant à payer]
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(Montant), BLANK(),
			        ABS(Montant) >= 1000000000, FORMAT(DIVIDE(Montant, 1000000000), "0.00", "fr-FR") & " Md XOF",
			        ABS(Montant) >= 1000000, FORMAT(DIVIDE(Montant, 1000000), "0.0", "fr-FR") & " M XOF",
			        FORMAT(Montant, "#,0", "fr-FR") & " XOF"
			    )
		lineageTag: 19493d71-c0ab-44d5-b3db-d1407cf5b78b

	measure 'Date de référence conformité' = FORMAT(MAX(ComplianceTrackingTable[Date_Référence]), "dd MMM yyyy", "fr-FR")
		lineageTag: 681d2190-6c72-4709-bc14-094c2d2765ff

	measure 'État global conformité' =
			VAR Lignes = COUNTROWS(ComplianceTrackingTable)
			VAR StatutsDisponibles =
			    COUNTROWS(
			        FILTER(
			            ComplianceTrackingTable,
			            NOT ISBLANK(ComplianceTrackingTable[Statut opérationnel])
			                && ComplianceTrackingTable[Statut opérationnel] <> ""
			        )
			    )
			VAR ÀPréparer =
			    COUNTROWS(
			        FILTER(ComplianceTrackingTable, ComplianceTrackingTable[Statut opérationnel] = "À préparer")
			    )
			RETURN
			    SWITCH(
			        TRUE(),
			        Lignes = 0 || StatutsDisponibles = 0, "DONNÉES À ACTUALISER",
			        [Actions immédiates] > 0, "ATTENTION REQUISE",
			        [À faire bientôt] > 0, "À PRÉPARER",
			        [Dossiers à confirmer] > 0, "À CONFIRMER",
			        ÀPréparer > 0, "À PRÉPARER",
			        "DOSSIER À JOUR"
			    )
		lineageTag: 5ecca656-9097-4e8c-a574-95fe42774d12

	measure 'Résumé conformité' =
			VAR Actions = [Actions immédiates]
			VAR Bientôt = [À faire bientôt]
			VAR Pièces = [Pièces à compléter]
			VAR PhraseActions =
			    SWITCH(
			        TRUE(),
			        Actions = 0, "Aucune action urgente.",
			        Actions = 1, "1 action demande votre attention.",
			        FORMAT(Actions, "0") & " actions demandent votre attention."
			    )
			VAR PhraseBientôt = IF(Bientôt > 0, " " & FORMAT(Bientôt, "0") & " échéance(s) sont à préparer dans les 30 jours.", "")
			VAR PhrasePièces = IF(Pièces > 0, " " & FORMAT(Pièces, "0") & " pièce(s) restent à compléter.", "")
			RETURN PhraseActions & PhraseBientôt & PhrasePièces
		lineageTag: 22e5d751-83f3-4d90-abfa-7f771477dba7

	measure 'Obligation sélectionnée' = SELECTEDVALUE(ComplianceObligationTable[Obligation], "Plusieurs obligations")
		lineageTag: 86b79a3a-feee-49e2-8c52-06a7db47b136

	measure 'Organisme sélectionné' = SELECTEDVALUE(ComplianceObligationTable[Organisme], "Organisme à confirmer")
		lineageTag: d7c53c77-c727-4056-8805-5567ae1f944e

	measure 'Statut du dossier' = SELECTEDVALUE(ComplianceTrackingTable[Statut opérationnel], "Sélection multiple")
		lineageTag: 93a05393-4d17-4e12-bcfa-92b03219e099

	measure 'Référence du dossier' = SELECTEDVALUE(ComplianceTrackingTable[Suivi_ID], "")
		lineageTag: d7c15a12-8109-46dc-8b17-2229128eec0f

	measure 'Échéance du dossier' =
			VAR DateÉchéance = SELECTEDVALUE(ComplianceTrackingTable[Date_Échéance])
			RETURN IF(ISBLANK(DateÉchéance), "À confirmer", FORMAT(DateÉchéance, "dd MMM yyyy", "fr-FR"))
		lineageTag: 5c857024-6e20-4b6d-87a2-1382c293e059

	measure 'Résumé du dossier' =
			VAR Organisme = [Organisme sélectionné]
			VAR Statut = [Statut du dossier]
			VAR Action = SELECTEDVALUE(ComplianceTrackingTable[Action requise], "Consulter les éléments du dossier")
			RETURN Organisme & " • " & Statut & " — " & Action
		lineageTag: 296763a6-3dce-40ec-8b81-23ca8edd6687

	measure 'Montant dû affiché' = FORMAT(COALESCE(SUM(ComplianceTrackingTable[Montant_Dû]), 0), "#,0", "fr-FR") & " XOF"
		lineageTag: 9e50045a-2818-4848-b83f-71c28c26c26a

	measure 'Montant payé affiché' = FORMAT(COALESCE(SUM(ComplianceTrackingTable[Montant_Payé]), 0), "#,0", "fr-FR") & " XOF"
		lineageTag: 5c63a3e1-6976-47b3-9811-5385ce43545b

	column Suivi_ID
		dataType: string
		lineageTag: a227bd48-be55-4c69-95a0-bfcac43eeb6e
		summarizeBy: none
		sourceColumn: Suivi_ID

	column Obligation_ID
		dataType: string
		lineageTag: 48d68a0f-d5b7-42fb-ab11-fdf3c3b3f884
		summarizeBy: none
		sourceColumn: Obligation_ID

	column Période
		dataType: string
		lineageTag: 000d4758-7936-4c12-acce-7600f90d63c9
		summarizeBy: none
		sourceColumn: Période

	column Date_Clé
		dataType: int64
		formatString: 0
		lineageTag: 7aafdbec-8eb4-4fa8-bb8e-91d4df8aeab9
		summarizeBy: none
		sourceColumn: Date_Clé

	column Date_Échéance
		dataType: dateTime
		formatString: Short Date
		lineageTag: 6b8d631e-3d1c-4693-af46-609c92003eb5
		summarizeBy: none
		sourceColumn: Date_Échéance
		annotation UnderlyingDateTimeDataType = Date

	column Date_Référence
		dataType: dateTime
		formatString: Short Date
		lineageTag: 548f71c5-f294-4a33-926e-dbc914683bf2
		summarizeBy: none
		sourceColumn: Date_Référence
		annotation UnderlyingDateTimeDataType = Date

	column Date_Déclaration
		dataType: dateTime
		formatString: Short Date
		lineageTag: 06d44871-ea90-4912-9e4b-ce5c9d7e9970
		summarizeBy: none
		sourceColumn: Date_Déclaration
		annotation UnderlyingDateTimeDataType = Date

	column Date_Paiement
		dataType: dateTime
		formatString: Short Date
		lineageTag: 47856a98-b2c8-4ee3-bcf8-43732641d4eb
		summarizeBy: none
		sourceColumn: Date_Paiement
		annotation UnderlyingDateTimeDataType = Date

	column Montant_Déclaré
		dataType: int64
		formatString: #,0
		lineageTag: abd369b0-87e0-428d-b99c-2278a976c712
		summarizeBy: sum
		sourceColumn: Montant_Déclaré

	column Montant_Dû
		dataType: int64
		formatString: #,0
		lineageTag: d4ca4c60-6e25-4555-a798-7c7642db41e4
		summarizeBy: sum
		sourceColumn: Montant_Dû

	column Montant_Payé
		dataType: int64
		formatString: #,0
		lineageTag: 987a6873-6ecd-4915-9c6f-fcb29bf560cc
		summarizeBy: sum
		sourceColumn: Montant_Payé

	column Responsable_Client
		dataType: string
		lineageTag: bbee5e55-4cf8-4421-a7f3-ce3307ce0a02
		summarizeBy: none
		sourceColumn: Responsable_Client

	column Référence_Déclaration
		dataType: string
		lineageTag: dd657b26-ae3a-4265-9a13-ea429a550320
		summarizeBy: none
		sourceColumn: Référence_Déclaration

	column Référence_Paiement
		dataType: string
		lineageTag: 57d82ddd-3b63-4ff2-8bf6-601a9d6cec25
		summarizeBy: none
		sourceColumn: Référence_Paiement

	column Statut_Saisi
		dataType: string
		lineageTag: 0228f108-c464-4372-b94d-666e8b491be8
		summarizeBy: none
		sourceColumn: Statut_Saisi

	column Commentaire
		dataType: string
		lineageTag: 039f2080-22a0-451c-820c-8f1e0306a438
		summarizeBy: none
		sourceColumn: Commentaire

	column Contrôle_Obligation
		dataType: string
		lineageTag: 5c7abf79-6f28-4795-b7bf-b748bc8eca04
		summarizeBy: none
		sourceColumn: Contrôle_Obligation

	column 'Statut opérationnel'
		dataType: string
		lineageTag: f42ee752-5a81-46c7-8a35-c12bb475aa0f
		summarizeBy: none
		sourceColumn: Statut opérationnel

	column Jours_Restants
		dataType: int64
		formatString: 0
		lineageTag: 3bd7758b-84be-4293-bc2a-94687d076678
		summarizeBy: none
		sourceColumn: Jours_Restants

	column Écart_Paiement
		dataType: int64
		formatString: #,0
		lineageTag: aecff65d-832a-4228-ad5e-0422d444fa56
		summarizeBy: sum
		sourceColumn: Écart_Paiement

	column 'État pièce'
		dataType: string
		lineageTag: 2e827960-b312-4b2a-86fb-28da66c76500
		summarizeBy: none
		sourceColumn: État pièce

	column 'Action requise'
		dataType: string
		lineageTag: d94647bd-123b-4945-a54a-78fb8fcc5afd
		summarizeBy: none
		sourceColumn: Action requise

	column Priorité_Affichage
		dataType: int64
		formatString: 0
		lineageTag: 97faa598-6bd2-49ee-9f99-0c17843d4803
		summarizeBy: none
		sourceColumn: Priorité_Affichage

	partition ComplianceTrackingTable = m
		mode: import
		source =
				let
				    Files = SharePoint.Files("https://ivorygoldconsulting-my.sharepoint.com/personal/augustin_kpadonou_ivorygoldglobal_com", [ApiVersion = 15]),
				    Source = Excel.Workbook(Files{[Name="Hotel_2_Fevrier_Donnees_Demo_PowerBI.xlsx"]}[Content], null, true),
				    TrackingRaw = Source{[Item="ComplianceTrackingTable",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(TrackingRaw,{{"Suivi_ID", type text}, {"Obligation_ID", type text}, {"Période", type text}, {"Date_Clé", Int64.Type}, {"Date_Échéance", type date}, {"Date_Référence", type date}, {"Date_Déclaration", type date}, {"Date_Paiement", type date}, {"Montant_Déclaré", Int64.Type}, {"Montant_Dû", Int64.Type}, {"Montant_Payé", Int64.Type}, {"Responsable_Client", type text}, {"Référence_Déclaration", type text}, {"Référence_Paiement", type text}, {"Statut_Saisi", type text}, {"Commentaire", type text}, {"Contrôle_Obligation", type text}}),
				    ObligationsRaw = Source{[Item="ComplianceObligationTable",Kind="Table"]}[Data],
				    ObligationsTyped = Table.TransformColumnTypes(ObligationsRaw,{{"Obligation_ID", type text}, {"Applicabilité", type text}, {"Preuve_Requise", type logical}}),
				    ObligationLookup = Table.SelectColumns(ObligationsTyped,{"Obligation_ID", "Applicabilité", "Preuve_Requise"}),
				    #"Merged obligations" = Table.NestedJoin(#"Changed Type", {"Obligation_ID"}, ObligationLookup, {"Obligation_ID"}, "_Obligation", JoinKind.LeftOuter),
				    #"Expanded obligations" = Table.ExpandTableColumn(#"Merged obligations", "_Obligation", {"Applicabilité", "Preuve_Requise"}, {"Applicabilité_Mat", "Preuve_Requise_Mat"}),
				    ReconciliationRaw = Source{[Item="ComplianceReconciliationTable",Kind="Table"]}[Data],
				    ReconciliationTyped = Table.TransformColumnTypes(ReconciliationRaw,{{"Suivi_ID", type text}, {"Écart_Comptabilité", Int64.Type}, {"Statut_Preuve", type text}}),
				    ReconciliationGrouped = Table.Group(
				        ReconciliationTyped,
				        {"Suivi_ID"},
				        {
				            {"Écart_Comptable_Mat", each List.Sum(List.Transform(List.RemoveNulls([Écart_Comptabilité]), each Number.Abs(_))), type number},
				            {"Nombre_Pièces_Mat", each Table.RowCount(_), Int64.Type},
				            {"Pièces_Disponibles_Mat", each Table.RowCount(Table.SelectRows(_, each [Statut_Preuve] = "Disponible")), Int64.Type},
				            {"Pièces_ÀCompléter_Mat", each Table.RowCount(Table.SelectRows(_, each List.Contains({"Manquant", "À obtenir"}, [Statut_Preuve]))), Int64.Type}
				        }
				    ),
				    #"Merged reconciliation" = Table.NestedJoin(#"Expanded obligations", {"Suivi_ID"}, ReconciliationGrouped, {"Suivi_ID"}, "_Reconciliation", JoinKind.LeftOuter),
				    #"Expanded reconciliation" = Table.ExpandTableColumn(#"Merged reconciliation", "_Reconciliation", {"Écart_Comptable_Mat", "Nombre_Pièces_Mat", "Pièces_Disponibles_Mat", "Pièces_ÀCompléter_Mat"}, {"Écart_Comptable_Mat", "Nombre_Pièces_Mat", "Pièces_Disponibles_Mat", "Pièces_ÀCompléter_Mat"}),
				    #"Added days remaining" = Table.AddColumn(#"Expanded reconciliation", "Jours_Restants", each if [Date_Échéance] = null or [Date_Référence] = null then null else Duration.Days([Date_Échéance] - [Date_Référence]), Int64.Type),
				    #"Added payment gap" = Table.AddColumn(#"Added days remaining", "Écart_Paiement", each List.Max({0, (if [Montant_Dû] = null then 0 else [Montant_Dû]) - (if [Montant_Payé] = null then 0 else [Montant_Payé])}), Int64.Type),
				    #"Added operational status" = Table.AddColumn(
				        #"Added payment gap",
				        "Statut opérationnel",
				        each
				            let
				                StatutSaisi = Text.Trim(if [Statut_Saisi] = null then "" else Text.From([Statut_Saisi])),
				                Applicabilite = Text.Trim(if [Applicabilité_Mat] = null then "" else Text.From([Applicabilité_Mat])),
				                EcartComptable = if [Écart_Comptable_Mat] = null then 0 else Number.From([Écart_Comptable_Mat]),
				                MontantDu = if [Montant_Dû] = null then 0 else [Montant_Dû],
				                MontantPaye = if [Montant_Payé] = null then 0 else [Montant_Payé],
				                Jours = [Jours_Restants]
				            in
				                if StatutSaisi = "À confirmer" or Applicabilite = "À confirmer" then "À confirmer"
				                else if [Date_Échéance] = null or [Date_Référence] = null then "À confirmer"
				                else if EcartComptable > 0 then "Écart à justifier"
				                else if StatutSaisi = "Clôturé" and (([Date_Déclaration] <> null and [Date_Déclaration] > [Date_Échéance]) or ([Date_Paiement] <> null and [Date_Paiement] > [Date_Échéance])) then "Fait hors délai"
				                else if StatutSaisi = "Clôturé" then "À jour"
				                else if [Date_Échéance] < [Date_Référence] and [Date_Déclaration] <> null and MontantDu > MontantPaye then "Paiement en attente"
				                else if [Date_Échéance] < [Date_Référence] then "En retard"
				                else if Jours <> null and Jours <= 7 then "Urgent"
				                else if Jours <> null and Jours <= 30 then "À faire bientôt"
				                else "À préparer",
				        type text
				    ),
				    #"Added evidence state" = Table.AddColumn(
				        #"Added operational status",
				        "État pièce",
				        each
				            let
				                PreuveRequise = [Preuve_Requise_Mat],
				                NombrePieces = if [Nombre_Pièces_Mat] = null then 0 else [Nombre_Pièces_Mat],
				                Disponibles = if [Pièces_Disponibles_Mat] = null then 0 else [Pièces_Disponibles_Mat],
				                ACompleter = if [Pièces_ÀCompléter_Mat] = null then 0 else [Pièces_ÀCompléter_Mat]
				            in
				                if PreuveRequise = false then "Non requise"
				                else if PreuveRequise = null or NombrePieces = 0 then "À confirmer"
				                else if Disponibles = NombrePieces then "Disponible"
				                else if ACompleter > 0 then "À compléter"
				                else "À confirmer",
				        type text
				    ),
				    #"Added required action" = Table.AddColumn(
				        #"Added evidence state",
				        "Action requise",
				        each
				            if [#"Statut opérationnel"] = "En retard" then "Régulariser l'échéance"
				            else if [#"Statut opérationnel"] = "Paiement en attente" then "Effectuer le paiement"
				            else if [#"Statut opérationnel"] = "Écart à justifier" then "Expliquer l'écart comptable"
				            else if [#"Statut opérationnel"] = "Urgent" then "Finaliser le dossier"
				            else if [#"Statut opérationnel"] = "À faire bientôt" then "Préparer le dossier"
				            else if [#"Statut opérationnel"] = "À confirmer" then "Confirmer l'applicabilité"
				            else if [#"État pièce"] = "À compléter" then "Joindre le justificatif"
				            else if [#"Statut opérationnel"] = "À préparer" then "Aucune action immédiate"
				            else if [#"Statut opérationnel"] = "Fait hors délai" then "Archivé — hors délai"
				            else "Dossier à jour",
				        type text
				    ),
				    #"Added display priority" = Table.AddColumn(
				        #"Added required action",
				        "Priorité_Affichage",
				        each
				            if [#"Statut opérationnel"] = "En retard" then 1
				            else if [#"Statut opérationnel"] = "Paiement en attente" then 2
				            else if [#"Statut opérationnel"] = "Écart à justifier" then 3
				            else if [#"Statut opérationnel"] = "Urgent" then 4
				            else if [#"Statut opérationnel"] = "À faire bientôt" then 5
				            else if [#"Statut opérationnel"] = "À confirmer" then 6
				            else if [#"Statut opérationnel"] = "À préparer" then 7
				            else if [#"Statut opérationnel"] = "Fait hors délai" then 8
				            else 9,
				        Int64.Type
				    ),
				    #"Removed helper columns" = Table.RemoveColumns(#"Added display priority", {"Applicabilité_Mat", "Preuve_Requise_Mat", "Écart_Comptable_Mat", "Nombre_Pièces_Mat", "Pièces_Disponibles_Mat", "Pièces_ÀCompléter_Mat"})
				in
				    #"Removed helper columns"

	annotation PBI_NavigationStepName = Navigation
	annotation PBI_ResultType = Table
