table ComplianceTrackingTable
	lineageTag: 6ae5b441-1c3a-4ade-9a10-139511a79146

	measure 'Échéances suivies' = COUNTROWS(ComplianceTrackingTable)
		formatString: 0
		lineageTag: 935268b5-c378-4449-893d-53c96ab29a0d

	measure 'Obligations suivies' = DISTINCTCOUNT(ComplianceTrackingTable[Obligation_ID])
		formatString: 0
		lineageTag: 2e15d9c7-9caa-4862-b8b7-c5f9c8677d2f

	measure 'Échéances conformes' = [Dossiers à jour]
		formatString: 0
		lineageTag: eb844e53-92f8-4310-9574-cb42c6dace0b

	measure 'Échéances à traiter' = [Actions immédiates]
		formatString: 0
		lineageTag: 43cb74a9-c303-4e29-a377-bb7481963734

	measure 'Taux de conformité' =
			VAR BaseÉvaluable = [Dossiers à jour] + [Actions immédiates]
			RETURN DIVIDE([Dossiers à jour], BaseÉvaluable)
		formatString: 0.0%
		lineageTag: 44d0dfc0-e5e0-4599-9158-3c00507b1f49

	measure 'Échéances dans 30 jours' = [À faire bientôt]
		formatString: 0
		lineageTag: 5b046117-da6f-4d69-ae10-54cdecd8cacc

	measure 'Dossiers à jour' =
			COALESCE(COUNTROWS(ComplianceDetailCurrent), 0)
		formatString: 0
		lineageTag: 3b60ee55-d714-4f67-92cf-875b95bbdb15

	measure 'Actions immédiates' =
			COALESCE(COUNTROWS(ComplianceDetailActions), 0)
		formatString: 0
		lineageTag: 6ee4691f-e13b-4d3d-9a97-5255676c8cad

	measure 'À faire bientôt' =
			COALESCE(COUNTROWS(ComplianceDetailSoon), 0)
		formatString: 0
		lineageTag: a1adec64-4260-4a3c-b3f9-8113e13c56f2

	measure 'Dossiers à confirmer' =
			COALESCE(COUNTROWS(ComplianceDetailConfirm), 0)
		formatString: 0
		lineageTag: 9d9e2d57-426c-40a8-92dd-a5bfd3a7a0b8

	measure 'Dossiers à préparer' =
			COALESCE(COUNTROWS(ComplianceDetailPrepare), 0)
		formatString: 0
		lineageTag: 03ce9a3a-5b57-4d64-8962-b4ea4f2c2c10


	measure 'Montant restant à payer' =
			SUMX(
			    ComplianceTrackingTable,
			    MAX(0, COALESCE(ComplianceTrackingTable[Montant_Dû], 0) - COALESCE(ComplianceTrackingTable[Montant_Payé], 0))
			)
		formatString: #,0
		lineageTag: fbcd8f99-07b4-4c73-857b-d1c1a23adff8

	measure 'Montant restant affiché' =
			VAR Montant = [Montant restant à payer]
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(Montant), BLANK(),
			        ABS(Montant) >= 1000000000, FORMAT(DIVIDE(Montant, 1000000000), "0.00", "fr-FR") & " Md XOF",
			        ABS(Montant) >= 1000000, FORMAT(DIVIDE(Montant, 1000000), "0.0", "fr-FR") & " M XOF",
			        FORMAT(Montant, "#,0", "fr-FR") & " XOF"
			    )
		lineageTag: 19493d71-c0ab-44d5-b3db-d1407cf5b78b

	measure 'Date de référence conformité' = FORMAT(MAX(ComplianceTrackingTable[Date_Référence]), "dd MMM yyyy", "fr-FR")
		lineageTag: 681d2190-6c72-4709-bc14-094c2d2765ff

	measure 'Statut conformité affiché' =
			[État global conformité] & "  ·  " & [Date de référence conformité]
		lineageTag: aabfc61a-5c77-4f54-a63c-3223b8dccf01

	measure 'État global conformité' =
			VAR Lignes = [Échéances suivies]
			VAR Actions = [Actions immédiates]
			VAR Bientot = [À faire bientôt]
			VAR AConfirmer = [Dossiers à confirmer]
			VAR APreparer = [Dossiers à préparer]
			VAR Pieces = COALESCE([Pièces à compléter], 0)
			VAR Salaries = COALESCE([Salariés à régulariser], 0)
			RETURN
			    SWITCH(
			        TRUE(),
			        Lignes = 0, "DONNÉES À ACTUALISER",
			        Actions > 0 || Pieces > 0 || Salaries > 0, "ATTENTION REQUISE",
			        AConfirmer > 0, "À CONFIRMER",
			        Bientot > 0 || APreparer > 0, "À PRÉPARER",
			        "DOSSIER À JOUR"
			    )
		lineageTag: 5ecca656-9097-4e8c-a574-95fe42774d12

	measure 'Résumé conformité' =
			VAR Actions = [Actions immédiates]
			VAR Bientôt = [À faire bientôt]
			VAR Pièces = [Pièces à compléter]
			VAR PhraseActions =
			    SWITCH(
			        TRUE(),
			        Actions = 0, "Aucune action urgente.",
			        Actions = 1, "1 action demande votre attention.",
			        FORMAT(Actions, "0") & " actions demandent votre attention."
			    )
			VAR PhraseBientôt = IF(Bientôt > 0, " " & FORMAT(Bientôt, "0") & " échéance(s) sont à préparer dans les 30 jours.", "")
			VAR PhrasePièces = IF(Pièces > 0, " " & FORMAT(Pièces, "0") & " pièce(s) restent à compléter.", "")
			RETURN PhraseActions & PhraseBientôt & PhrasePièces
		lineageTag: 22e5d751-83f3-4d90-abfa-7f771477dba7

	measure 'Obligation sélectionnée' = SELECTEDVALUE(ComplianceObligationTable[Obligation], "Plusieurs obligations")
		lineageTag: 86b79a3a-feee-49e2-8c52-06a7db47b136

	measure 'Organisme sélectionné' = SELECTEDVALUE(ComplianceObligationTable[Organisme], "Organisme à confirmer")
		lineageTag: d7c53c77-c727-4056-8805-5567ae1f944e

	measure 'Statut du dossier' = SELECTEDVALUE(ComplianceTrackingTable[Statut lecture], "Sélection multiple")
		lineageTag: 93a05393-4d17-4e12-bcfa-92b03219e099

	measure 'Référence du dossier' = SELECTEDVALUE(ComplianceTrackingTable[Suivi_ID], "")
		lineageTag: d7c15a12-8109-46dc-8b17-2229128eec0f

	measure 'Échéance du dossier' =
			VAR DateÉchéance = SELECTEDVALUE(ComplianceTrackingTable[Date_Échéance])
			RETURN IF(ISBLANK(DateÉchéance), "À confirmer", FORMAT(DateÉchéance, "dd MMM yyyy", "fr-FR"))
		lineageTag: 5c857024-6e20-4b6d-87a2-1382c293e059

	measure 'Résumé du dossier' =
			VAR Organisme = [Organisme sélectionné]
			VAR Statut = [Statut du dossier]
			VAR Action = [Action du dossier]
			RETURN Organisme & " • " & Statut & " — " & Action
		lineageTag: 296763a6-3dce-40ec-8b81-23ca8edd6687

	measure 'Montant dû affiché' = FORMAT(COALESCE(SUM(ComplianceTrackingTable[Montant_Dû]), 0), "#,0", "fr-FR") & " XOF"
		lineageTag: 9e50045a-2818-4848-b83f-71c28c26c26a

	measure 'Montant payé affiché' = FORMAT(COALESCE(SUM(ComplianceTrackingTable[Montant_Payé]), 0), "#,0", "fr-FR") & " XOF"
		lineageTag: 5c63a3e1-6976-47b3-9811-5385ce43545b

	measure 'Reste à payer dossier affiché' =
			VAR Du = COALESCE(SELECTEDVALUE(ComplianceTrackingTable[Montant_Dû]), 0)
			VAR Paye = COALESCE(SELECTEDVALUE(ComplianceTrackingTable[Montant_Payé]), 0)
			VAR Reste = MAX(0, Du - Paye)
			RETURN FORMAT(Reste, "#,0", "fr-FR") & " XOF"
		lineageTag: 99fc02ef-36db-4f20-8a2b-7ed513b30db2

	measure 'Action du dossier' = SELECTEDVALUE(ComplianceTrackingTable[Action lecture], "Consulter le dossier")
		lineageTag: 91dd15af-daa5-4a30-87a2-893524101bd1

	column Suivi_ID
		dataType: string
		lineageTag: a227bd48-be55-4c69-95a0-bfcac43eeb6e
		summarizeBy: none
		sourceColumn: Suivi_ID

	column Obligation_ID
		dataType: string
		lineageTag: 48d68a0f-d5b7-42fb-ab11-fdf3c3b3f884
		summarizeBy: none
		sourceColumn: Obligation_ID

	column Période
		dataType: string
		lineageTag: 000d4758-7936-4c12-acce-7600f90d63c9
		summarizeBy: none
		sourceColumn: Période

	column Date_Clé
		dataType: int64
		formatString: 0
		lineageTag: 7aafdbec-8eb4-4fa8-bb8e-91d4df8aeab9
		summarizeBy: none
		sourceColumn: Date_Clé

	column Date_Échéance
		dataType: dateTime
		formatString: Short Date
		lineageTag: 6b8d631e-3d1c-4693-af46-609c92003eb5
		summarizeBy: none
		sourceColumn: Date_Échéance
		annotation UnderlyingDateTimeDataType = Date

	column Date_Référence
		dataType: dateTime
		formatString: Short Date
		lineageTag: 548f71c5-f294-4a33-926e-dbc914683bf2
		summarizeBy: none
		sourceColumn: Date_Référence
		annotation UnderlyingDateTimeDataType = Date

	column Date_Déclaration
		dataType: dateTime
		formatString: Short Date
		lineageTag: 06d44871-ea90-4912-9e4b-ce5c9d7e9970
		summarizeBy: none
		sourceColumn: Date_Déclaration
		annotation UnderlyingDateTimeDataType = Date

	column Date_Paiement
		dataType: dateTime
		formatString: Short Date
		lineageTag: 47856a98-b2c8-4ee3-bcf8-43732641d4eb
		summarizeBy: none
		sourceColumn: Date_Paiement
		annotation UnderlyingDateTimeDataType = Date

	column Montant_Déclaré
		dataType: int64
		formatString: #,0
		lineageTag: abd369b0-87e0-428d-b99c-2278a976c712
		summarizeBy: sum
		sourceColumn: Montant_Déclaré

	column Montant_Dû
		dataType: int64
		formatString: #,0
		lineageTag: d4ca4c60-6e25-4555-a798-7c7642db41e4
		summarizeBy: sum
		sourceColumn: Montant_Dû

	column Montant_Payé
		dataType: int64
		formatString: #,0
		lineageTag: 987a6873-6ecd-4915-9c6f-fcb29bf560cc
		summarizeBy: sum
		sourceColumn: Montant_Payé

	column Responsable_Client
		dataType: string
		lineageTag: bbee5e55-4cf8-4421-a7f3-ce3307ce0a02
		summarizeBy: none
		sourceColumn: Responsable_Client

	column Référence_Déclaration
		dataType: string
		lineageTag: dd657b26-ae3a-4265-9a13-ea429a550320
		summarizeBy: none
		sourceColumn: Référence_Déclaration

	column Référence_Paiement
		dataType: string
		lineageTag: 57d82ddd-3b63-4ff2-8bf6-601a9d6cec25
		summarizeBy: none
		sourceColumn: Référence_Paiement

	column Statut_Saisi
		dataType: string
		lineageTag: 0228f108-c464-4372-b94d-666e8b491be8
		summarizeBy: none
		sourceColumn: Statut_Saisi

	column Commentaire
		dataType: string
		lineageTag: 039f2080-22a0-451c-820c-8f1e0306a438
		summarizeBy: none
		sourceColumn: Commentaire

	column Contrôle_Obligation
		dataType: string
		lineageTag: 5c7abf79-6f28-4795-b7bf-b748bc8eca04
		summarizeBy: none
		sourceColumn: Contrôle_Obligation

	column 'Statut lecture' =
			VAR StatutSaisi = TRIM(COALESCE(ComplianceTrackingTable[Statut_Saisi], ""))
			VAR DateRef = ComplianceTrackingTable[Date_Référence]
			VAR DateEch = ComplianceTrackingTable[Date_Échéance]
			VAR DateDecl = ComplianceTrackingTable[Date_Déclaration]
			VAR DatePay = ComplianceTrackingTable[Date_Paiement]
			VAR MontantDu = COALESCE(ComplianceTrackingTable[Montant_Dû], 0)
			VAR MontantPaye = COALESCE(ComplianceTrackingTable[Montant_Payé], 0)
			VAR Jours = IF(NOT ISBLANK(DateRef) && NOT ISBLANK(DateEch), DATEDIFF(DateRef, DateEch, DAY))
			RETURN
			    SWITCH(
			        TRUE(),
			        StatutSaisi = "À confirmer", "À confirmer",
			        ISBLANK(DateRef) || ISBLANK(DateEch), "À confirmer",
			        StatutSaisi = "Clôturé" &&
			            (
			                (NOT ISBLANK(DateDecl) && DateDecl > DateEch)
			                    || (NOT ISBLANK(DatePay) && DatePay > DateEch)
			            ), "Fait hors délai",
			        StatutSaisi = "Clôturé", "À jour",
			        DateEch < DateRef && NOT ISBLANK(DateDecl) && MontantDu > MontantPaye, "Paiement en attente",
			        DateEch < DateRef, "En retard",
			        Jours <= 7, "Urgent",
			        Jours <= 30, "À faire bientôt",
			        "À préparer"
			    )
		dataType: string
		lineageTag: 5d54d8c9-7759-43a3-891f-0a8c696c0aa1
		summarizeBy: none

	column 'Jours restants lecture' =
			IF(
			    ISBLANK(ComplianceTrackingTable[Date_Échéance]) || ISBLANK(ComplianceTrackingTable[Date_Référence]),
			    BLANK(),
			    DATEDIFF(ComplianceTrackingTable[Date_Référence], ComplianceTrackingTable[Date_Échéance], DAY)
			)
		dataType: int64
		formatString: 0
		lineageTag: 3952c5f0-f469-4ff0-b58f-f629032b969b
		summarizeBy: none

	column 'Reste paiement lecture' =
			MAX(
			    0,
			    COALESCE(ComplianceTrackingTable[Montant_Dû], 0)
			        - COALESCE(ComplianceTrackingTable[Montant_Payé], 0)
			)
		dataType: int64
		formatString: #,0
		lineageTag: 63ed7f15-4837-4a44-92f6-2dd1a2c64a9d
		summarizeBy: sum

	column 'Action lecture' =
			SWITCH(
			    ComplianceTrackingTable[Statut lecture],
			    "En retard", "Régulariser l'échéance",
			    "Paiement en attente", "Effectuer le paiement",
			    "Urgent", "Finaliser le dossier",
			    "À faire bientôt", "Préparer le dossier",
			    "À confirmer", "Confirmer les informations",
			    "À préparer", "Aucune action immédiate",
			    "Fait hors délai", "Archivé — hors délai",
			    "Dossier à jour"
			)
		dataType: string
		lineageTag: 042fe9f8-2bb2-4383-a98e-5f099f1a4e1e
		summarizeBy: none


	partition ComplianceTrackingTable = m
		mode: import
		source =
				let
				    Files = SharePoint.Files("https://ivorygoldconsulting-my.sharepoint.com/personal/augustin_kpadonou_ivorygoldglobal_com", [ApiVersion = 15]),
				    Source = Excel.Workbook(Files{[Name="Hotel_2_Fevrier_Donnees_Demo_PowerBI.xlsx"]}[Content], null, true),
				    ComplianceTrackingTable_Table = Source{[Item="ComplianceTrackingTable",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(ComplianceTrackingTable_Table,{{"Suivi_ID", type text}, {"Obligation_ID", type text}, {"Période", type text}, {"Date_Clé", Int64.Type}, {"Date_Échéance", type date}, {"Date_Référence", type date}, {"Date_Déclaration", type date}, {"Date_Paiement", type date}, {"Montant_Déclaré", Int64.Type}, {"Montant_Dû", Int64.Type}, {"Montant_Payé", Int64.Type}, {"Responsable_Client", type text}, {"Référence_Déclaration", type text}, {"Référence_Paiement", type text}, {"Statut_Saisi", type text}, {"Commentaire", type text}, {"Contrôle_Obligation", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation
	annotation PBI_ResultType = Table
