table OrderTable
	lineageTag: 150139d1-7e83-4a58-9c36-c2cf014a3ba2

	measure 'Chiffre d''affaires' =
			
			CALCULATE(
			    SUM(OrderTable[Montant_TTC]),
			    OrderTable[Type_Commande] = "Vente",
			    OrderTable[Statut] = "Terminée"
			)
		formatString: 0
		lineageTag: b08b3791-f3d0-4348-bf5f-08471b2cd259

	measure 'CA Hébergement' =
			COALESCE(
			    CALCULATE(
			        [Chiffre d'affaires],
			        FILTER(
			            VALUES(OrderTable[Catégorie]),
			            VAR Categorie = UPPER(COALESCE(OrderTable[Catégorie], ""))
			            RETURN CONTAINSSTRING(Categorie, "HÉBERGEMENT") || CONTAINSSTRING(Categorie, "HEBERGEMENT")
			        )
			    ),
			    0
			)
		formatString: 0
		lineageTag: 9f4d9b60-c9ec-4c72-88d4-3044134b9db8

	measure 'CA Restaurant' =
			COALESCE(
			    CALCULATE(
			        [Chiffre d'affaires],
			        FILTER(
			            VALUES(OrderTable[Catégorie]),
			            CONTAINSSTRING(UPPER(COALESCE(OrderTable[Catégorie], "")), "RESTAUR")
			        )
			    ),
			    0
			)
		formatString: 0
		lineageTag: a5fa32ae-a3a0-4d97-b017-4fb1b1c91d22

	measure 'CA Bar' =
			COALESCE(
			    CALCULATE(
			        [Chiffre d'affaires],
			        FILTER(
			            VALUES(OrderTable[Catégorie]),
			            CONTAINSSTRING(UPPER(COALESCE(OrderTable[Catégorie], "")), "BAR")
			        )
			    ),
			    0
			)
		formatString: 0
		lineageTag: 8f6cc89e-c230-412c-b3d4-550659f42f3a

	measure 'CA Autres' =
			COALESCE([Chiffre d'affaires] - [CA Hébergement] - [CA Restaurant] - [CA Bar], 0)
		formatString: 0
		lineageTag: e8a8d515-4ad3-46c7-8380-cb7970da2d6c

	measure Achats =
			
			CALCULATE(
			    SUM(OrderTable[Montant_TTC]),
			    OrderTable[Type_Commande] = "Achat",
			    OrderTable[Statut] = "Terminée"
			)
		formatString: 0
		lineageTag: 3d1274f5-3699-476f-8737-ba10c84cfe07

	measure 'Chiffre d''affaires affiché' =
			VAR Montant = [Chiffre d'affaires]
			VAR ValeurAbsolue = ABS(Montant)
			RETURN
			SWITCH(
			    TRUE(),
			    ISBLANK(Montant), BLANK(),
			    ValeurAbsolue >= 1000000000, FORMAT(DIVIDE(Montant, 1000000000), "0.00", "fr-FR") & " Md XOF",
			    ValeurAbsolue >= 1000000, FORMAT(DIVIDE(Montant, 1000000), "0.0", "fr-FR") & " M XOF",
			    FORMAT(Montant, "#,0", "fr-FR") & " XOF"
			)
		lineageTag: b57c22b0-b9a4-46da-87e4-6f78eaaef240

	measure 'Évolution CA dernier mois' =
			VAR DateFin = MAX(DateTable[Date])
			VAR DateDebut = DATE(YEAR(DateFin), MONTH(DateFin), 1)
			VAR DateFinPrecedente = EDATE(DateFin, -1)
			VAR DateDebutPrecedente = DATE(YEAR(DateFinPrecedente), MONTH(DateFinPrecedente), 1)
			VAR Actuel = CALCULATE([Chiffre d'affaires], REMOVEFILTERS(DateTable), DATESBETWEEN(DateTable[Date], DateDebut, DateFin))
			VAR Precedent = CALCULATE([Chiffre d'affaires], REMOVEFILTERS(DateTable), DATESBETWEEN(DateTable[Date], DateDebutPrecedente, DateFinPrecedente))
			RETURN IF(ISBLANK(Precedent) || Precedent = 0, BLANK(), DIVIDE(Actuel - Precedent, ABS(Precedent)))
		formatString: 0.0%
		lineageTag: 69c9ce6a-d609-4ff3-9442-1190bed5790f

	measure 'Évolution CA affichée' =
			VAR Evolution = [Évolution CA dernier mois]
			RETURN IF(ISBLANK(Evolution), "Comparaison indisponible", IF(Evolution >= 0, "▲ ", "▼ ") & FORMAT(ABS(Evolution), "0.0 %", "fr-FR") & " vs mois préc.")
		lineageTag: 6ee2b64c-aa4d-4ce7-9880-9432fe0f7fd3

	measure 'Couleur évolution CA' =
			VAR Evolution = [Évolution CA dernier mois]
			RETURN SWITCH(TRUE(), ISBLANK(Evolution), "#667085", Evolution >= 0, "#2FA79B", "#EB5757")
		lineageTag: 0d71d16c-a82e-45ff-8829-26ad23c1dc23

	column Commande_ID
		dataType: string
		lineageTag: 49144fc1-295b-4459-8cf4-e6398b3958fb
		summarizeBy: none
		sourceColumn: Commande_ID

		annotation SummarizationSetBy = Automatic

	column Type_Commande
		dataType: string
		lineageTag: 42220d7c-15e8-46c2-b296-8cede5b27b3a
		summarizeBy: none
		sourceColumn: Type_Commande

		annotation SummarizationSetBy = Automatic

	column Date_Clé
		dataType: int64
		formatString: 0
		lineageTag: 44ac4c58-c9a3-4c3a-9d68-43151f6eed33
		summarizeBy: none
		sourceColumn: Date_Clé

		annotation SummarizationSetBy = Automatic

	column Date_Commande
		dataType: dateTime
		formatString: Long Date
		lineageTag: c6a216bf-0192-4ca5-bffa-732d4ec929aa
		summarizeBy: none
		sourceColumn: Date_Commande

		variation Variation
			isDefault
			relationship: a41b0123-720c-4562-b441-abdc3cdff53c
			defaultHierarchy: LocalDateTable_f9cca8e7-271d-4d2a-9edd-1a664d936877.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Partenaire_ID
		dataType: string
		lineageTag: 895708c5-bd1a-4650-a520-ff96cd073110
		summarizeBy: none
		sourceColumn: Partenaire_ID

		annotation SummarizationSetBy = Automatic

	column Nom_Partenaire
		dataType: string
		lineageTag: 96f8d207-ff10-4684-8ac0-a3d9e7841b75
		summarizeBy: none
		sourceColumn: Nom_Partenaire

		annotation SummarizationSetBy = Automatic

	column Catégorie
		dataType: string
		lineageTag: 15001fc7-976c-4713-852b-4bb1eff77d30
		summarizeBy: none
		sourceColumn: Catégorie

		annotation SummarizationSetBy = Automatic

	column Activité_CA
		dataType: string
		lineageTag: 32d632ae-5ebd-4b95-8df0-bd6f49b9af70
		summarizeBy: none
		sourceColumn: Activité_CA

		annotation SummarizationSetBy = Automatic

	column Montant_HT
		dataType: int64
		formatString: 0
		lineageTag: df1b979a-84b2-43a7-9f94-e77b66f53b97
		summarizeBy: sum
		sourceColumn: Montant_HT

		annotation SummarizationSetBy = Automatic

	column TVA
		dataType: int64
		formatString: 0
		lineageTag: 780a1ecb-b0c8-4f38-bc5f-1a23f50b3a58
		summarizeBy: sum
		sourceColumn: TVA

		annotation SummarizationSetBy = Automatic

	column Retenue
		dataType: int64
		formatString: 0
		lineageTag: 26fbd144-52e4-4e92-8747-c80fc7166a59
		summarizeBy: sum
		sourceColumn: Retenue

		annotation SummarizationSetBy = Automatic

	column Montant_TTC
		dataType: int64
		formatString: 0
		lineageTag: 1b971b5f-9cd4-42bb-8e9f-99703d8cf3e3
		summarizeBy: sum
		sourceColumn: Montant_TTC

		annotation SummarizationSetBy = Automatic

	column Statut
		dataType: string
		lineageTag: 78f1ce06-8a48-4462-b30a-da02fc2754ae
		summarizeBy: none
		sourceColumn: Statut

		annotation SummarizationSetBy = Automatic

	column Date_Livraison_Prévue
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6775cc92-ebb8-4925-b97c-e199dd10daaa
		summarizeBy: none
		sourceColumn: Date_Livraison_Prévue

		variation Variation
			isDefault
			relationship: 2687307c-baf8-42a2-b1df-f49292f16560
			defaultHierarchy: LocalDateTable_360deeae-5e06-4cde-9935-b880ade67f79.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Date_Livraison_Réelle
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1d08ed08-242e-4f3a-9558-4ced6da700ac
		summarizeBy: none
		sourceColumn: Date_Livraison_Réelle

		variation Variation
			isDefault
			relationship: 56119d91-3de9-46cf-9059-6d1c4ca59543
			defaultHierarchy: LocalDateTable_f9d9161a-d48e-41a5-8634-fd76754e1afb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Livrée_À_Temps
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ea675c63-4b85-4050-978e-ec3fd1c1678c
		summarizeBy: none
		sourceColumn: Livrée_À_Temps

		annotation SummarizationSetBy = Automatic

	partition OrderTable = m
		mode: import
		source =
				let
				    Files = SharePoint.Files("https://ivorygoldconsulting-my.sharepoint.com/personal/augustin_kpadonou_ivorygoldglobal_com", [ApiVersion = 15]),
				    Source = Excel.Workbook(Files{[Name="Hotel_2_Fevrier_Donnees_Demo_PowerBI.xlsx"]}[Content], null, true),
				    OrderTable_Table = Source{[Item="OrderTable",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(OrderTable_Table,{{"Commande_ID", type text}, {"Type_Commande", type text}, {"Date_Clé", Int64.Type}, {"Date_Commande", type date}, {"Partenaire_ID", type text}, {"Nom_Partenaire", type text}, {"Catégorie", type text}, {"Montant_HT", Int64.Type}, {"TVA", Int64.Type}, {"Retenue", Int64.Type}, {"Montant_TTC", Int64.Type}, {"Statut", type text}, {"Date_Livraison_Prévue", type date}, {"Date_Livraison_Réelle", type date}, {"Livrée_À_Temps", type logical}}),
				    #"Added Activity" = Table.AddColumn(
				        #"Changed Type",
				        "Activité_CA",
				        each
				            let
				                Category = Text.Upper(Text.Trim(if [Catégorie] = null then "" else Text.From([Catégorie])))
				            in
				                if Text.Contains(Category, "HÉBERGEMENT") or Text.Contains(Category, "HEBERGEMENT") then "Hébergement"
				                else if Text.Contains(Category, "RESTAUR") then "Restaurant"
				                else if Text.Contains(Category, "BAR") then "Bar"
				                else "Autres",
				        type text
				    )
				in
				    #"Added Activity"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
